# travis-ci does not have first-class support for octave
language: python

install:
  - export
  - sudo add-apt-repository ppa:octave/stable -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq octave

script: make test
